name: Pointed
version: '${project.version}'
main: dev.felnull.pointed.Pointed
api-version: '1.19'
depend:
  - BetterGUI
commands:
  pointed:
    permission: pointed.command.admin
    aliases: [ptd]
  ptreward:
    aliases: [ptr]
  mypoint:
    aliases: [myp]
  ranking:
    aliases: [ ranking ]
permissions:
  pointed.command.admin:
    default: op
  pointed.command.player:
    default: true