name: Pointed
version: '${project.version}'
main: dev.felnull.pointed.Pointed
api-version: '1.16'
depend:
  - BetterGUI
commands:
  pt:
    permission: pointed.admin
    description: Pointed commands
    usage: "/pt <getnow|gettotal|get|add|sub|set|rank>"
  ptteam:
    permission: pointed.admin
    description: Pointed commands
    usage: "/ptteam <>"
  reward:
    permission: pointed.player

permissions:
  pointed.admin:
    default: op
  pointed.player:
    default: true